project:
  type: book

book:
  title: "Python for Business Analytics and Informaton Systems"
  author: "Markum Reed"
  date: "Updated: Summer 2024"
  chapters:
    - index.qmd
    - intro.qmd
    - 01_python_install_env_setup.qmd # all
    - 02_python_basics.qmd # all
    - 03_python_control_structures.qmd # all
    - 04_python_functions_modules.qmd # all
    - 05_python_data_handling_file_io.qmd # all
    - 06_python_error_handling_debugging.qmd # all
    - 07_python_oop.qmd # all
    - 08_python_database_interaction.qmd  # sys_analy_design
    - 09_python_api_interaction.qmd # sys_analy_design
    - 10_python_automated_sys_tasks.qmd # sys_analy_design
    - 11_python_testing.qmd # sys_analy_design
    - 12_python_adv_concepts.qmd # sys_analy_design
    - 13_python_lib_for_sys_design.qmd # sys_analy_design
    - 14_foundations_of_data_comm.qmd # bus_data_comm
    - 15_network_architecture_protocols.qmd # bus_data_comm
    - 16_network_services_mgmt.qmd # bus_data_comm
    - 17_adv_network_concepts.qmd # bus_data_comm
    - 18_modern_network_practices.qmd # bus_data_comm
    - summary.qmd
    - A1_version_control.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



